#!/bin/zsh
#
# (Re)generate the Claude Code settings and link them into ~/.claude.
# settings.json is generated by merging the tracked base settings with
# machine-local private overrides (untracked). Re-run this script
# (or `dot claude-link`) after editing either file.
# Idempotent: safe to re-run any time. Called by install.sh on bootstrap.
set -eo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"

echo "--- Create symbolic link of Claude Code configuration ---"
mkdir -p ${HOME}/.claude
test -f ${DOTFILES_DIR}/claude/settings.private.json || echo '{}' > ${DOTFILES_DIR}/claude/settings.private.json
jq -s '.[0] * .[1]' ${DOTFILES_DIR}/claude/settings.base.json ${DOTFILES_DIR}/claude/settings.private.json > ${DOTFILES_DIR}/claude/settings.json
rm -f ${HOME}/.claude/settings.json ${HOME}/.claude/CLAUDE.md
ln -sn ${DOTFILES_DIR}/claude/settings.json ${HOME}/.claude/settings.json
ln -sn ${DOTFILES_DIR}/claude/CLAUDE.md ${HOME}/.claude/CLAUDE.md
